import { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  {
    levelNumber: 1,
    name: 'Cráter Base',
    subtitle: 'Ascenso inicial tranquilo',
    worldHeight: 2400,
    lavaSpeed: 25, // Lava suave y relajada para que subir sea fácil
    rockSpawnRate: 3.8, // Rocas poco frecuentes
    rockSpeedMin: 110,
    rockSpeedMax: 180,
    movingPlatforms: false,
    crumblyPlatforms: false,
    description: 'Un ascenso relajado y amigable. Las plataformas son anchas y la lava sube despacio para que escales con tranquilidad.',
  },
  {
    levelNumber: 2,
    name: 'Cavernas de Ceniza',
    subtitle: 'Flotando entre el humo',
    worldHeight: 2800,
    lavaSpeed: 33,
    rockSpawnRate: 3.0,
    rockSpeedMin: 130,
    rockSpeedMax: 210,
    movingPlatforms: true,
    crumblyPlatforms: false,
    description: 'Plataformas flotantes de movimiento lento y suave. La lava mantiene un ritmo pausado y fácil de superar.',
  },
  {
    levelNumber: 3,
    name: 'Túneles de Obsidiana',
    subtitle: 'Puentes de basalto',
    worldHeight: 3200,
    lavaSpeed: 42,
    rockSpawnRate: 2.4,
    rockSpeedMin: 160,
    rockSpeedMax: 250,
    movingPlatforms: true,
    crumblyPlatforms: true,
    description: 'Aparecen algunas rocas quebradizas de ceniza. El ascenso sigue siendo cómodo con buen margen de reacción.',
  },
  {
    levelNumber: 4,
    name: 'Conducto Magmático',
    subtitle: 'El calor asciende',
    worldHeight: 3600,
    lavaSpeed: 52,
    rockSpawnRate: 1.9,
    rockSpeedMin: 190,
    rockSpeedMax: 290,
    movingPlatforms: true,
    crumblyPlatforms: true,
    description: 'Caminos entrecortados con plataformas móviles. Ritmo activo y entretenido pero muy accesible.',
  },
  {
    levelNumber: 5,
    name: 'Chimenea Volcánica',
    subtitle: 'Vapores ardientes',
    worldHeight: 4000,
    lavaSpeed: 62,
    rockSpawnRate: 1.5,
    rockSpeedMin: 220,
    rockSpeedMax: 330,
    movingPlatforms: true,
    crumblyPlatforms: true,
    description: 'El magma ruge y las chispas vuelan. La antesala al sector más emocionante y desafiante.',
  },
  {
    levelNumber: 6,
    name: 'La Caldera Ardiente',
    subtitle: '¡Zona Difícil de Alto Riesgo!',
    worldHeight: 4500,
    lavaSpeed: 76, // ¡Aquí la lava se vuelve rápida y desafiante!
    rockSpawnRate: 1.1, // Lluvia continua de rocas
    rockSpeedMin: 260,
    rockSpeedMax: 420,
    movingPlatforms: true,
    crumblyPlatforms: true,
    description: '¡Aquí empieza el verdadero reto! La lava sube con rapidez, caen ráfagas de piedras incandescentes y las plataformas son más exigentes.',
  },
  {
    levelNumber: 7,
    name: 'Cúspide en Erupción',
    subtitle: 'Escape supremo a la cumbre',
    worldHeight: 4800,
    lavaSpeed: 88,
    rockSpawnRate: 0.95,
    rockSpeedMin: 280,
    rockSpeedMax: 450,
    movingPlatforms: true,
    crumblyPlatforms: true,
    description: '¡Erupción máxima apocalíptica! Esquiva la intensa lluvia de meteoros volcánicos y llega al helicóptero de rescate.',
  },
];

